name: 'ProjectA-MiddlewareA'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'ProjectA-MiddlewareA/*'

pool:
  name: 'ado-201-pool'

variables:
  dir-name: 'AKS-Backend'
  app-name: 'middelware-api'
  dockerRegistryServiceConnection: '9668d2b2-2021-4667-b776-92289773592d'
  imageRepository: '$(app-name)'
  containerRegistry: 'acr201new.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/$(dir-name)/Dockerfile'
  tag: 'dev-$(Build.SourceVersion)'
  # Git envs
  ado-project: 'RVRIT'
  ado-repo: 'Middeleware-ArgoCD'
  ado-branch: main
  # App
  value-file-dev: 'values_dev.yaml'


stages:
- stage: Build_Docker_Image
  displayName: Build and push docker image
  jobs:
  - job: Build
    displayName: Build and push docker image
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: '$(dir-name)/pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build the image 
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push the image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: DEV_Update_Image_Tag_Helm_Chart
  displayName: DEV - Update Helm chart with new image tag, Git update and push stage
  jobs:
  - job: Git_DEV
    displayName: Git update and push
    steps:
    - checkout: git://$(ado-project)/$(ado-repo)@$(ado-branch)
      persistCredentials: true
    - task: Bash@3
      displayName: DEV - Update values files with new image tag and push to the Git repo 
      inputs:
        targetType: 'inline'
        script: |
          git checkout $(ado-branch)
          git pull --all
          git config user.name "ADO Pipeline"
          sed -i '0,/^\([[:space:]]*tag: *\).*/s//\1$(tag)/;' Helmcharts/$(app-name)/$(value-file-dev)
          git commit -a -m 'Updated image tag to $(tag)'
          git push -u origin $(ado-branch)
